[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "crewai-chat-ui"
version = "0.1.0"
authors = [{ name = "CrewAI Chat UI", email = "example@example.com" }]
description = "Web UI for CrewAI chat functionality"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["crewai>=0.105.0", "flask>=2.0.0", "click>=8.0.0"]

[project.scripts]
crewai-chat-ui = "crewai_chat_ui.server:main"

[project.urls]
"Homepage" = "https://github.com/yourusername/crewai-chat-ui"
"Bug Tracker" = "https://github.com/yourusername/crewai-chat-ui/issues"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["crewai_chat_ui*"]

[tool.setuptools.package-data]
crewai_chat_ui = ["static/*"]
